"""Added user contact details and location  to Request

Revision ID: 34eaca270554
Revises: 8eb5ab31e1fa
Create Date: 2024-05-06 18:35:40.607425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34eaca270554'
down_revision = '8eb5ab31e1fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('user_contact', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_column('user_contact')
        batch_op.drop_column('username')
        batch_op.drop_column('distance')

    # ### end Alembic commands ###
