"""Added created and updated date  to Request

Revision ID: 745e403dd834
Revises: 34eaca270554
Create Date: 2024-05-07 00:44:13.192590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '745e403dd834'
down_revision = '34eaca270554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
